### ISSUE TITLE
Domaine Ina

### ISSUE THREAD

**Issue by arthaud-proust** [les-voix-errantes-de-kyiv/6-ina#1]
# Configuration du sous domaine de votre projet

1. Ajoutez "6-ina.les-voix-errantes-de-kyiv.fr" en tant que nom de domaine sur votre hébergeur (vercel, netlify, etc)

2. **Répondez ci-dessous quel hébergeur vous utilisez pour que je fasse pointer le domaine dessus.**

Dispo pour toute question

**Comment by samuelabadie** [comment]
Netlify

**Comment by arthaud-proust** [comment]
top, le domaine est lié. le TLS se mets en place, d'ici 10 min y'aura le https

**Comment by arthaud-proust** [comment]
Hello,
Vous pouvez ajouter le nom de domaine `ina.les-voix-errantes-de-kyiv.fr` dans votre hébergeur.
L'ancienne adresse redirigera vers la nouvelle, comme ça si vous avez fait un qr code il fonctionnera toujours.
